services:
  api:
    build: ./api
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    command: 
    - -p $API_PORT
    depends_on:
      - prometheus
      - jaeger
      - alloy
      - loki

  web:
    build:  ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env

  prometheus:
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    image: prom/prometheus:latest
    command:
    - --config.file=/etc/prometheus/prometheus.yml 
  
  grafana:
    ports:
      - "3000:3000"
    image: grafana/grafana-oss
    depends_on:
      - loki
      - prometheus

  jaeger:
    ports:
        - 6831:6831/udp
        - 5778:5778
        - 16686:16686
        #       - 4318:4318
        - 14269:14269
        - 14268:14268
    image: jaegertracing/all-in-one:latest
  
  loki:
    image: grafana/loki:3.1.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - "./loki/config.yaml:/etc/loki/local-config.yaml"
  
  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    ports:
      - "12345:12345"
    command: 
    - run
    - --server.http.listen-addr=0.0.0.0:12345
    - --storage.path=/var/lib/alloy/data
    - --stability.level=experimental
    - /etc/alloy/config.alloy

volumes:
    file_dir:
    log_dir: 


