services:
  api:
    build: ./api
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    command: 
    - -p $API_PORT
    depends_on:
      - alloy

  web:
    build:  ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env

  prometheus:
    build: ./Prometheus
    ports:
      - "9090:9090"
    depends_on:
      - api
  
  grafana:
    ports:
      - "3000:3000"
    image: grafana/grafana-oss
    depends_on:
      - loki
      - prometheus
      - jaeger

  jaeger:
    ports:
        - 6831:6831/udp
        - 5778:5778
        - 16686:16686
        - 14269:14269
        - 14268:14268
    image: jaegertracing/all-in-one:latest
  
  loki:
    build: ./loki
    ports:
      - "3100:3100"
  
  alloy:
    build: ./alloy
    ports:
      - "12345:12345"
    depends_on:
      - jaeger
      - loki

volumes:
    file_dir:
    log_dir: 


